services:
  marketplace-adapter-rest-api:
    build:
      context: .
      dockerfile: ./apps/marketplace-adapter-rest-api/Dockerfile
    ports:
      - "3013:3000"
    env_file:
      - ./packages/common/.env
