/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type SignatureRSVStruct = {
  r: BytesLike;
  s: BytesLike;
  v: BigNumberish;
};

export type SignatureRSVStructOutput = [r: string, s: string, v: bigint] & {
  r: string;
  s: string;
  v: bigint;
};

export declare namespace PolyBet {
  export type BetSlipStruct = {
    strategy: BigNumberish;
    initialCollateral: BigNumberish;
    finalCollateral: BigNumberish;
    outcomeIndex: BigNumberish;
    status: BigNumberish;
    failureReason: string;
    marketplaceIds: BytesLike[];
    marketIds: BytesLike[];
    proxiedBets: BytesLike[];
  };

  export type BetSlipStructOutput = [
    strategy: bigint,
    initialCollateral: bigint,
    finalCollateral: bigint,
    outcomeIndex: bigint,
    status: bigint,
    failureReason: string,
    marketplaceIds: string[],
    marketIds: string[],
    proxiedBets: string[],
  ] & {
    strategy: bigint;
    initialCollateral: bigint;
    finalCollateral: bigint;
    outcomeIndex: bigint;
    status: bigint;
    failureReason: string;
    marketplaceIds: string[];
    marketIds: string[];
    proxiedBets: string[];
  };

  export type MarketplaceStruct = {
    warpRouterId: BigNumberish;
    chainId: BigNumberish;
    chainFamily: BigNumberish;
    name: string;
    marketplaceProxy: string;
    pricingStrategy: BigNumberish;
  };

  export type MarketplaceStructOutput = [
    warpRouterId: bigint,
    chainId: bigint,
    chainFamily: bigint,
    name: string,
    marketplaceProxy: string,
    pricingStrategy: bigint,
  ] & {
    warpRouterId: bigint;
    chainId: bigint;
    chainFamily: bigint;
    name: string;
    marketplaceProxy: string;
    pricingStrategy: bigint;
  };

  export type ProxiedBetStruct = {
    id: BytesLike;
    betSlipId: BigNumberish;
    marketplaceId: BigNumberish;
    marketId: BigNumberish;
    optionIndex: BigNumberish;
    minimumShares: BigNumberish;
    blockTimestamp: BigNumberish;
    originalCollateralAmount: BigNumberish;
    finalCollateralAmount: BigNumberish;
    sharesBought: BigNumberish;
    sharesSold: BigNumberish;
    outcome: BigNumberish;
    failureReason: string;
  };

  export type ProxiedBetStructOutput = [
    id: string,
    betSlipId: bigint,
    marketplaceId: bigint,
    marketId: bigint,
    optionIndex: bigint,
    minimumShares: bigint,
    blockTimestamp: bigint,
    originalCollateralAmount: bigint,
    finalCollateralAmount: bigint,
    sharesBought: bigint,
    sharesSold: bigint,
    outcome: bigint,
    failureReason: string,
  ] & {
    id: string;
    betSlipId: bigint;
    marketplaceId: bigint;
    marketId: bigint;
    optionIndex: bigint;
    minimumShares: bigint;
    blockTimestamp: bigint;
    originalCollateralAmount: bigint;
    finalCollateralAmount: bigint;
    sharesBought: bigint;
    sharesSold: bigint;
    outcome: bigint;
    failureReason: string;
  };
}

export interface PolyBetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addMarketplace"
      | "betSlips"
      | "domain"
      | "getBetSlip"
      | "getMarketplace"
      | "getProxiedBet"
      | "getUserActiveBetslips()"
      | "getUserActiveBetslips(bytes)"
      | "getUserBalance(bytes)"
      | "getUserBalance()"
      | "getUserClosedBets(bytes)"
      | "getUserClosedBets()"
      | "initiateSellProxiedBets"
      | "login"
      | "marketplaces"
      | "musdcToken"
      | "owner"
      | "placeBet"
      | "proxiedBets"
      | "recordProxiedBetClosed"
      | "recordProxiedBetPlaced"
      | "recordProxiedBetSold"
      | "renounceOwnership"
      | "setCollateralToken"
      | "transferOwnership"
      | "updateBetSlipStatus"
      | "userActiveBetSlips"
      | "userClosedBetSlips"
      | "withdrawWinnings"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "BetSlipCreated" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addMarketplace",
    values: [BigNumberish, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "betSlips",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "domain", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getBetSlip",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketplace",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProxiedBet",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserActiveBetslips()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserActiveBetslips(bytes)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBalance(bytes)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBalance()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserClosedBets(bytes)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserClosedBets()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initiateSellProxiedBets",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "login",
    values: [string, SignatureRSVStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "marketplaces",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "musdcToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeBet",
    values: [BigNumberish, BigNumberish, BigNumberish, BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiedBets",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordProxiedBetClosed",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordProxiedBetPlaced",
    values: [BigNumberish, PolyBet.ProxiedBetStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "recordProxiedBetSold",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCollateralToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBetSlipStatus",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userActiveBetSlips",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userClosedBetSlips",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawWinnings",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addMarketplace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "betSlips", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "domain", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBetSlip", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMarketplace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProxiedBet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserActiveBetslips()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserActiveBetslips(bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBalance(bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBalance()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserClosedBets(bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserClosedBets()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateSellProxiedBets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "login", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marketplaces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "musdcToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiedBets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordProxiedBetClosed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordProxiedBetPlaced",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordProxiedBetSold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCollateralToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBetSlipStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userActiveBetSlips",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userClosedBetSlips",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawWinnings",
    data: BytesLike
  ): Result;
}

export namespace BetSlipCreatedEvent {
  export type InputTuple = [
    betId: BigNumberish,
    totalCollateralAmount: BigNumberish,
    marketplaceIds: BytesLike[],
    marketIds: BytesLike[],
  ];
  export type OutputTuple = [
    betId: bigint,
    totalCollateralAmount: bigint,
    marketplaceIds: string[],
    marketIds: string[],
  ];
  export interface OutputObject {
    betId: bigint;
    totalCollateralAmount: bigint;
    marketplaceIds: string[];
    marketIds: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PolyBet extends BaseContract {
  connect(runner?: ContractRunner | null): PolyBet;
  waitForDeployment(): Promise<this>;

  interface: PolyBetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addMarketplace: TypedContractMethod<
    [
      chainId: BigNumberish,
      family: BigNumberish,
      name: string,
      marketplaceProxy: string,
    ],
    [void],
    "nonpayable"
  >;

  betSlips: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, string] & {
        strategy: bigint;
        initialCollateral: bigint;
        finalCollateral: bigint;
        outcomeIndex: bigint;
        status: bigint;
        failureReason: string;
      },
    ],
    "view"
  >;

  domain: TypedContractMethod<[], [string], "view">;

  getBetSlip: TypedContractMethod<
    [betSlipId: BigNumberish],
    [PolyBet.BetSlipStructOutput],
    "view"
  >;

  getMarketplace: TypedContractMethod<
    [marketplaceId: BigNumberish],
    [PolyBet.MarketplaceStructOutput],
    "view"
  >;

  getProxiedBet: TypedContractMethod<
    [betId: BytesLike],
    [PolyBet.ProxiedBetStructOutput],
    "view"
  >;

  "getUserActiveBetslips()": TypedContractMethod<[], [bigint[]], "view">;

  "getUserActiveBetslips(bytes)": TypedContractMethod<
    [authToken: BytesLike],
    [bigint[]],
    "view"
  >;

  "getUserBalance(bytes)": TypedContractMethod<
    [authToken: BytesLike],
    [bigint],
    "view"
  >;

  "getUserBalance()": TypedContractMethod<[], [bigint], "view">;

  "getUserClosedBets(bytes)": TypedContractMethod<
    [authToken: BytesLike],
    [bigint[]],
    "view"
  >;

  "getUserClosedBets()": TypedContractMethod<[], [bigint[]], "view">;

  initiateSellProxiedBets: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: BigNumberish, arg3: boolean],
    [void],
    "view"
  >;

  login: TypedContractMethod<
    [siweMsg: string, sig: SignatureRSVStruct],
    [string],
    "view"
  >;

  marketplaces: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string, string, bigint] & {
        warpRouterId: bigint;
        chainId: bigint;
        chainFamily: bigint;
        name: string;
        marketplaceProxy: string;
        pricingStrategy: bigint;
      },
    ],
    "view"
  >;

  musdcToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  placeBet: TypedContractMethod<
    [
      strategy: BigNumberish,
      totalCollateralAmount: BigNumberish,
      outcomeIndex: BigNumberish,
      marketplaceIds: BytesLike[],
      marketIds: BytesLike[],
    ],
    [void],
    "nonpayable"
  >;

  proxiedBets: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
      ] & {
        id: string;
        betSlipId: bigint;
        marketplaceId: bigint;
        marketId: bigint;
        optionIndex: bigint;
        minimumShares: bigint;
        blockTimestamp: bigint;
        originalCollateralAmount: bigint;
        finalCollateralAmount: bigint;
        sharesBought: bigint;
        sharesSold: bigint;
        outcome: bigint;
        failureReason: string;
      },
    ],
    "view"
  >;

  recordProxiedBetClosed: TypedContractMethod<
    [
      proxiedBetId: BytesLike,
      outcome: BigNumberish,
      winningsCollateralValue: BigNumberish,
    ],
    [void],
    "nonpayable"
  >;

  recordProxiedBetPlaced: TypedContractMethod<
    [betSlipId: BigNumberish, proxiedBet: PolyBet.ProxiedBetStruct],
    [void],
    "nonpayable"
  >;

  recordProxiedBetSold: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: BigNumberish],
    [void],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setCollateralToken: TypedContractMethod<
    [_musdcToken: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateBetSlipStatus: TypedContractMethod<
    [betSlipId: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  userActiveBetSlips: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  userClosedBetSlips: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  withdrawWinnings: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addMarketplace"
  ): TypedContractMethod<
    [
      chainId: BigNumberish,
      family: BigNumberish,
      name: string,
      marketplaceProxy: string,
    ],
    [void],
    "nonpayable"
  >;
  getFunction(nameOrSignature: "betSlips"): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, string] & {
        strategy: bigint;
        initialCollateral: bigint;
        finalCollateral: bigint;
        outcomeIndex: bigint;
        status: bigint;
        failureReason: string;
      },
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "domain"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getBetSlip"
  ): TypedContractMethod<
    [betSlipId: BigNumberish],
    [PolyBet.BetSlipStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarketplace"
  ): TypedContractMethod<
    [marketplaceId: BigNumberish],
    [PolyBet.MarketplaceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProxiedBet"
  ): TypedContractMethod<
    [betId: BytesLike],
    [PolyBet.ProxiedBetStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserActiveBetslips()"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserActiveBetslips(bytes)"
  ): TypedContractMethod<[authToken: BytesLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserBalance(bytes)"
  ): TypedContractMethod<[authToken: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserBalance()"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserClosedBets(bytes)"
  ): TypedContractMethod<[authToken: BytesLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserClosedBets()"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "initiateSellProxiedBets"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: BigNumberish, arg3: boolean],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "login"
  ): TypedContractMethod<
    [siweMsg: string, sig: SignatureRSVStruct],
    [string],
    "view"
  >;
  getFunction(nameOrSignature: "marketplaces"): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string, string, bigint] & {
        warpRouterId: bigint;
        chainId: bigint;
        chainFamily: bigint;
        name: string;
        marketplaceProxy: string;
        pricingStrategy: bigint;
      },
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "musdcToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "placeBet"
  ): TypedContractMethod<
    [
      strategy: BigNumberish,
      totalCollateralAmount: BigNumberish,
      outcomeIndex: BigNumberish,
      marketplaceIds: BytesLike[],
      marketIds: BytesLike[],
    ],
    [void],
    "nonpayable"
  >;
  getFunction(nameOrSignature: "proxiedBets"): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
      ] & {
        id: string;
        betSlipId: bigint;
        marketplaceId: bigint;
        marketId: bigint;
        optionIndex: bigint;
        minimumShares: bigint;
        blockTimestamp: bigint;
        originalCollateralAmount: bigint;
        finalCollateralAmount: bigint;
        sharesBought: bigint;
        sharesSold: bigint;
        outcome: bigint;
        failureReason: string;
      },
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordProxiedBetClosed"
  ): TypedContractMethod<
    [
      proxiedBetId: BytesLike,
      outcome: BigNumberish,
      winningsCollateralValue: BigNumberish,
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordProxiedBetPlaced"
  ): TypedContractMethod<
    [betSlipId: BigNumberish, proxiedBet: PolyBet.ProxiedBetStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordProxiedBetSold"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: BigNumberish],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCollateralToken"
  ): TypedContractMethod<[_musdcToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateBetSlipStatus"
  ): TypedContractMethod<
    [betSlipId: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userActiveBetSlips"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userClosedBetSlips"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawWinnings"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BetSlipCreated"
  ): TypedContractEvent<
    BetSlipCreatedEvent.InputTuple,
    BetSlipCreatedEvent.OutputTuple,
    BetSlipCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "BetSlipCreated(uint256,uint256,bytes32[],bytes32[])": TypedContractEvent<
      BetSlipCreatedEvent.InputTuple,
      BetSlipCreatedEvent.OutputTuple,
      BetSlipCreatedEvent.OutputObject
    >;
    BetSlipCreated: TypedContractEvent<
      BetSlipCreatedEvent.InputTuple,
      BetSlipCreatedEvent.OutputTuple,
      BetSlipCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
