/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "A13e",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.A13e__factory>;
    getContractFactory(
      name: "SiweAuth",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SiweAuth__factory>;
    getContractFactory(
      name: "EthereumUtils",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EthereumUtils__factory>;
    getContractFactory(
      name: "SiweParser",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SiweParser__factory>;
    getContractFactory(
      name: "PolyBet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PolyBet__factory>;

    getContractAt(
      name: "A13e",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.A13e>;
    getContractAt(
      name: "SiweAuth",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SiweAuth>;
    getContractAt(
      name: "EthereumUtils",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EthereumUtils>;
    getContractAt(
      name: "SiweParser",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SiweParser>;
    getContractAt(
      name: "PolyBet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PolyBet>;

    deployContract(
      name: "A13e",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.A13e>;
    deployContract(
      name: "SiweAuth",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SiweAuth>;
    deployContract(
      name: "EthereumUtils",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EthereumUtils>;
    deployContract(
      name: "SiweParser",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SiweParser>;
    deployContract(
      name: "PolyBet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PolyBet>;

    deployContract(
      name: "A13e",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.A13e>;
    deployContract(
      name: "SiweAuth",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SiweAuth>;
    deployContract(
      name: "EthereumUtils",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EthereumUtils>;
    deployContract(
      name: "SiweParser",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SiweParser>;
    deployContract(
      name: "PolyBet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PolyBet>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
