services:
  bet-router-rofl:
    build: .
    image: "ghcr.io/ethglobal-cannes-polybets/bet-router-rofl"
    platform: linux/amd64
    network_mode: host
    environment:
      - BASE_URL=${BASE_URL:-http://localhost:3000}
      - BET_EXECUTION_BASE_URL=${BET_EXECUTION_BASE_URL:-http://localhost:3000}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - SAPPHIRETESTNET_RPC_URL=${SAPPHIRETESTNET_RPC_URL}
      - POLYBETS_CONTRACT_ADDRESS=${POLYBETS_CONTRACT_ADDRESS:-0xaecDA91C878735D6a24A53EbE9C2F7b6c47C9454}
      - POLYBETS_CONTRACT_ABI_PATH=./contracts/PolyBet.json
